baseURL = 'https://blog.codsec.com/'
languageCode = 'en-us'
title = "y0ug's Internet Misadventure"
paginate = 10
googleAnalytics = 'G-SBZY0HP325'
theme = [ "github-maverick" ]

[author]
  name = "Hugo Caron"
  email = "hca443@gmail.com"

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "y0ug's internet misadventure around malware analysis, reverse enginering, homelab building, programming, devops"

[params.comments]
  githubRepo = 'y0ug/hugo-blog-codsec'
  theme = 'github-dark'

[params.twitter]
  creator = "y0ug"
  site = "y0ug"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = false 
  [markup.goldmark.parser]
	autoHeadingID = true
	autoHeadingIDType = 'github'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

  [markup.highlight]
    style = 'github'

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
